export const CREATE = "CREATE";
export const EDIT = "CREATE";
export const CHECKING_LOGIN = "CHECKING_LOGIN";
export const CHECK_TOKEN = "CHECK_TOKEN"
export const SET_TOKEN = "SET_TOKEN";
export const SHOW_LOGIN_FORM = "SHOW_LOGIN_FORM";
export const CHANGE_STATE = "CHANGE_STATE";
export const SELECT_PAGE = "SELECT_PAGE";
export const TASK_LOADING = "TASK_LOADING";
export const TASK_LOAD_SUCCESS = "TASK_LOAD_SUCCESS";
export const TASK_LOAD_FAIL = "TASK_LOAD_FAIL";
export const TASK_CREATING = "TASK_CREATING";
export const TASK_CREATE_SUCCESS = "TASK_CREATE_SUCCESS";
export const TASK_SAVING = "TASK_SAVING";
export const TASK_SAVE_SUCCESS = "TASK_SAVE_SUCCESS";
export const SHOW_ERROR = "SHOW_ERROR";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const CLOSE_MESSAGE = "CLOSE_MESSAGE";
export const CHANGE_SORT_ORDER = "CHANGE_SORT_ORDER";
export const CHANGE_SORT_FIELD = "CHANGE_SORT_FIELD";


